sudo: required

dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.phpbrew
    - $HOME/.npm

branches:
  only:
    - master
    - develop

# Before install, failures in this section will result in build status 'errored'
before_install:
  - |
    if [[ "$WP_VERSION" == "latest" ]]; then
      curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
      WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
    fi
  - |
    if [[ "$PHP" == "1" ]]; then
      git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
      cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/tests/phpunit/wp-tests-config.php
    fi

before_script:
  - npm install || exit 1
  - composer install
  - |
    if [[ "$PHP" == "1" ]]; then
      export WP_DEVELOP_DIR=/tmp/wordpress
      export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
      bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost
    fi

script:
  - npm run lint
  - npm run test:phpunit

jobs:
  allow_failures:
    - php: 7.4snapshot
  include:
    - name: PHP Tests (PHP 5.6, WordPress latest)
      php: 5.6
      env: WP_VERSION=latest PHP=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - name: PHP Tests (PHP 7.3, WordPress latest)
      php: 7.3
      env: WP_VERSION=latest PHP=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - name: PHP Tests (PHP 7.4, WordPress trunk)
      stage: test
      php: 7.4snapshot
      env: WP_VERSION=master PHP=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

services:
  - docker
