export const SET_AUTOSHARE_FOR_TWITTER_ENABLED = 'SET_AUTOSHARE_FOR_TWITTER_ENABLED';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_LOADED = 'SET_LOADED';
export const SET_OVERRIDING = 'SET_OVERRIDING';
export const SET_SAVING = 'SET_SAVING';
export const SET_TWEET_TEXT = 'SET_TWEET_TEXT';
