name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
    paths:
      - '**.js'
      - '**.php'
      - '**.css'

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        core:
          - { name: 'WP latest', version: 'latest' }
          - { name: 'WP trunk', version: 'WordPress/WordPress#master' }
          - { name: 'WP minimum', version: 'WordPress/WordPress#5.7' }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i && npm i -g cypress@9.0.0

      - name: Build asset
        run: npm run build

      - name: Add dependencies
        run: composer install -o --no-dev --ignore-platform-reqs

      - name: Set the core version
        run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

      - name: Set up WP environment
        run: npm run env:start

      - name: Test
        run: cypress run --config-file tests/cypress/config.json --env TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }},TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }},TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }},TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifact-autoshare-for-twitter
          retention-days: 2
          path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
