name: ESLint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
    paths: # Note: Update paths here will also require updating paths in ignore.eslint.yml.
      - '**.js'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v16
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: npm install
      run: npm install
    - name: Run eslint
      run: npm run lint