name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        job-name: eslint
     
  test_php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
    - name: PHP version
      run: php --version
    - name: Install dependencies
      run: composer install --ignore-platform-reqs
    - name: Run PHPCS
      if: matrix.php-versions == '7.3'
      run: composer run lint
    - name: Run PHPUnit
      run: |
        composer run setup-local-tests
        composer test
    - name: Run WP Acceptance
      if: matrix.php-versions == '7.3' || matrix.php-versions == '7.2'
      run: |
        WP_SNAPSHOTS_DIR=${{ github.workspace }}/.wpsnapshots/ ./vendor/bin/wpsnapshots configure --aws_key=${{ secrets.AWS_ACCESS_KEY }} --aws_secret=${{ secrets.SECRET_ACCESS_KEY }} --user_name="wp-acceptance" --user_email=travis@10up.com 10up
        ./vendor/bin/wpacceptance run
