name: Test

on:
  pull_request:
    branches:
      - develop
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        job-name: eslint
     
  test_php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: wordpress_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify MySQL connection
      run: |
        mysql --version
        echo ${{ job.services.mysql.ports['3306'] }}
        mysql --host=localhost --port=${{ job.services.mysql.ports['3306'] }} --protocol=tcp -uroot -proot -e "SHOW DATABASES"
    - name: Install dependencies
      run: composer install
    - name: Run PHPCS
      if: matrix.php-versions == '7.3'
      run: composer run lint
    - name: Run PHPUnit
      run: |
        composer run setup-local-tests
        composer test
