name: Tests

on:
  push:
    branches:
      - develop
      - trunk
      - feature/add-cypress-tests
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        job-name: eslint

  test_php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    strategy:
      matrix:
        php-versions: ['7.2', '7.3']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        extensions: mysql, imagick

  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        core:
          - { name: 'WP latest', version: 'latest' }
          - { name: 'WP minimum', version: 'WordPress/WordPress#5.2.11' }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i && npm i -g cypress@9.0.0

      - name: Build asset
        run: npm run build

      - name: Add dependencies
        run: composer install -o --no-dev --ignore-platform-reqs

      - name: Set the core version
        run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

      - name: Set up WP environment
        run: npm run wp-env start

      - name: Test
        run: cypress run --config-file tests/cypress/config.json --env TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }},TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }},TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }},TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-artifact-autoshare-for-twitter
          retention-days: 2
          path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
