name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WP_SNAPSHOTS_DIR: ${{ env.GITHUB_WORKSPACE }}/.wpsnapshots/
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      with:
        job-name: eslint
     
  test_php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: composer install
    - name: Run PHPCS
      if: matrix.php-versions == '7.3'
      run: composer run lint
    - name: Run PHPUnit
      run: |
        composer run setup-local-tests
        composer test
    - name: Run WP Acceptance
      if: matrix.php-versions == '7.2'
      run: |
        ./vendor/bin/wpsnapshots configure 10up --aws_key="$AWS_ACCESS_KEY" --aws_secret="$SECRET_ACCESS_KEY" --user_name=wp-acceptance --user_email=travis@10up.com
        ./vendor/bin/wpacceptance run
