name: Test

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: npm install
    - name: eslint
      uses: icrawl/action-eslint@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        job-name: eslint
     
  test_php:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none

    - name: Test
      run: ./bin/test.sh
      env:
        PHP_VERSION: ${{ matrix.php-versions }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
